### ISSUE TITLE
FYI

### ISSUE THREAD

**Issue by ukdtom** [timmy0209/WangYiYun.bundle#6]
https://forums.plex.tv/t/the-third-party-music-agent-is-missing-local-media-assets/817891

**Comment by ain-soph** [comment]
I see their recent commit about this: https://github.com/timmy0209/WangYiYun.bundle/commit/ab356dc8f03193aa5a63ff26a6cd3f13f4875386

**Comment by ukdtom** [comment]
Thanks...Since not following this Git
Would have been nice and decent of @timmy0209 to at least ack, when picking up !
